// prisma/seed.ts
import { PrismaClient } from '@prisma/client'
const prisma = new PrismaClient()

type SeedAccount = {
  code: string
  name: string
  offBalance: boolean
}

const accounts: SeedAccount[] = [
  // 01 – 19
  { code: '01',     name: 'Основные средства',                                                       offBalance: false },
  { code: '01.01',  name: 'Основные средства в организации',                                        offBalance: false },
  { code: '01.03',  name: 'Арендованное имущество',                                                   offBalance: false },
  { code: '01.05',  name: 'Затраты на ремонт основных средств',                                      offBalance: false },
  { code: '01.08',  name: 'Объекты недвижимости, права собственности на которые не зарегистрированы', offBalance: false },
  { code: '01.09',  name: 'Выбытие основных средств',                                                offBalance: false },
  { code: '01.11',  name: 'Групповые объекты основных средств',                                      offBalance: false },
  { code: '01.К',   name: 'Корректировка стоимости арендованного имущества',                         offBalance: false },

  { code: '02',     name: 'Амортизация основных средств',                                            offBalance: false },
  { code: '02.01',  name: 'Амортизация основных средств, учитываемых на счете 01',                  offBalance: false },
  { code: '02.02',  name: 'Амортизация основных средств, учитываемых на счете 03',                  offBalance: false },
  { code: '02.03',  name: 'Амортизация арендованного имущества',                                     offBalance: false },
  { code: '02.04',  name: 'Обесценение основных средств, учитываемых на счете 01',                  offBalance: false },
  { code: '02.05',  name: 'Амортизация затрат на ремонт основных средств',                           offBalance: false },
  { code: '02.11',  name: 'Амортизация групповых объектов основных средств',                        offBalance: false },

  { code: '03',     name: 'Доходные вложения в материальные ценности',                               offBalance: false },
  { code: '03.01',  name: 'Материальные ценности в организации',                                      offBalance: false },
  { code: '03.02',  name: 'Материальные ценности, предоставленные во временное владение и пользование', offBalance: false },
  { code: '03.03',  name: 'Материальные ценности, предоставленные во временное пользование',          offBalance: false },
  { code: '03.04',  name: 'Прочие доходные вложения',                                                 offBalance: false },
  { code: '03.09',  name: 'Выбытие материальных ценностей',                                          offBalance: false },

  { code: '04',     name: 'Нематериальные активы',                                                   offBalance: false },
  { code: '04.01',  name: 'Нематериальные активы организации',                                       offBalance: false },
  { code: '04.02',  name: 'Расходы на научно-исследовательские, опытно-конструкторские и технологические работы', offBalance: false },
  { code: '04.09',  name: 'Выбытие нематериальных активов',                                          offBalance: false },

  { code: '05',     name: 'Амортизация нематериальных активов',                                       offBalance: false },
  { code: '05.01',  name: 'Амортизация нематериальных активов',                                       offBalance: false },
  { code: '05.02',  name: 'Обесценение нематериальных активов',                                       offBalance: false },

  { code: '07',     name: 'Оборудование к установке',                                                 offBalance: false },
  { code: '08',     name: 'Вложения во внеоборотные активы',                                          offBalance: false },
  { code: '08.01',  name: 'Приобретение земельных участков',                                          offBalance: false },
  { code: '08.01.1',name: 'Приобретение земельных участков с доп. расходами',                         offBalance: false },
  { code: '08.01.2',name: 'Приобретение земельных участков без доп. расходов',                       offBalance: false },
  { code: '08.02',  name: 'Приобретение объектов природопользования',                                offBalance: false },
  { code: '08.03',  name: 'Строительство объектов основных средств',                                 offBalance: false },
  { code: '08.04',  name: 'Приобретение объектов основных средств',                                  offBalance: false },
  { code: '08.04.1',name: 'Приобретение компонентов основных средств',                               offBalance: false },
  { code: '08.04.2',name: 'Приобретение основных средств',                                           offBalance: false },
  { code: '08.04.5',name: 'Вложения в ремонты основных средств',                                      offBalance: false },
  { code: '08.05',  name: 'Приобретение нематериальных активов',                                      offBalance: false },
  { code: '08.06',  name: 'Перевод молодняка животных в основное стадо',                            offBalance: false },
  { code: '08.07',  name: 'Приобретение взрослых животных',                                          offBalance: false },
  { code: '08.08',  name: 'Выполнение научно-исследовательских, опытно-конструкторских и технологических работ', offBalance: false },
  { code: '08.11',  name: 'Нематериальные поисковые активы',                                         offBalance: false },
  { code: '08.12',  name: 'Материальные поисковые активы',                                            offBalance: false },

  { code: '09',     name: 'Отложенные налоговые активы',                                              offBalance: false },

  { code: '10',     name: 'Материалы',                                                             offBalance: false },
  { code: '10.01',  name: 'Сырье и материалы',                                                     offBalance: false },
  { code: '10.02',  name: 'Покупные полуфабрикаты и комплектующие изделия, конструкции и детали',    offBalance: false },
  { code: '10.03',  name: 'Топливо',                                                              offBalance: false },
  { code: '10.03.1',name: 'Топливо на складе',                                                    offBalance: false },
  { code: '10.03.2',name: 'Топливо в баке',                                                       offBalance: false },
  { code: '10.04',  name: 'Тара и тарные материалы',                                              offBalance: false },
  { code: '10.05',  name: 'Запасные части',                                                       offBalance: false },
  { code: '10.06',  name: 'Прочие материалы',                                                     offBalance: false },
  { code: '10.07',  name: 'Материалы, переданные в переработку на сторону',                       offBalance: false },
  { code: '10.08',  name: 'Строительные материалы',                                              offBalance: false },
  { code: '10.09',  name: 'Инвентарь и хозяйственные принадлежности',                             offBalance: false },
  { code: '10.10',  name: 'Специальная оснастка и специальная одежда на складе',                  offBalance: false },
  { code: '10.11',  name: 'Специальная оснастка и специальная одежда в эксплуатации',             offBalance: false },
  { code: '10.11.1',name: 'Специальная одежда в эксплуатации',                                    offBalance: false },
  { code: '10.11.2',name: 'Специальная оснастка в эксплуатации',                                   offBalance: false },
  { code: '10.21',  name: 'Малоценное оборудование и запасы',                                      offBalance: false },
  { code: '10.21.1',name: 'Приобретение малоценного оборудования и запасов',                       offBalance: false },
  { code: '10.21.2',name: 'Выбытие малоценного оборудования и запасов',                            offBalance: false },

  { code: '11',     name: 'Животные на выращивании и откорме',                                     offBalance: false },

  { code: '14',     name: 'Резервы под снижение стоимости материальных ценностей',                  offBalance: false },
  { code: '14.01',  name: 'Резервы под снижение стоимости материалов',                             offBalance: false },
  { code: '14.02',  name: 'Резервы под снижение стоимости товаров',                                offBalance: false },
  { code: '14.03',  name: 'Резервы под снижение стоимости готовой продукции',                      offBalance: false },
  { code: '14.04',  name: 'Резервы под снижение стоимости незавершенного производства',             offBalance: false },

  { code: '15',     name: 'Заготовление и приобретение материальных ценностей',                    offBalance: false },
  { code: '15.01',  name: 'Заготовление и приобретение материалов',                                offBalance: false },
  { code: '15.02',  name: 'Приобретение товаров',                                                  offBalance: false },

  { code: '16',     name: 'Отклонение в стоимости материальных ценностей',                        offBalance: false },
  { code: '16.01',  name: 'Отклонение в стоимости материалов',                                    offBalance: false },
  { code: '16.02',  name: 'Отклонение в стоимости товаров',                                       offBalance: false },

  { code: '19',     name: 'НДС по приобретенным ценностям',                                      offBalance: false },
  { code: '19.01',  name: 'НДС при приобретении основных средств',                                 offBalance: false },
  { code: '19.02',  name: 'НДС по приобретенным нематериальным активам',                         offBalance: false },
  { code: '19.03',  name: 'НДС по приобретенным материально-производственным запасам',             offBalance: false },
  { code: '19.04',  name: 'НДС по приобретенным услугам',                                        offBalance: false },
  { code: '19.05',  name: 'НДС, уплаченный при ввозе товаров на территорию Российской Федерации', offBalance: false },
  { code: '19.06',  name: 'Акцизы по оплаченным материальным ценностям',                        offBalance: false },
  { code: '19.07',  name: 'НДС по товарам, реализованным по ставке 0 % (экспорт)',               offBalance: false },
  { code: '19.08',  name: 'НДС при строительстве основных средств',                              offBalance: false },
  { code: '19.09',  name: 'НДС по уменьшению стоимости реализации',                              offBalance: false },
  { code: '19.10',  name: 'НДС, уплачиваемый при импорте из Таможенного союза',                  offBalance: false },

  // 20 – 42
  { code: '20',     name: 'Основное производство',                                                offBalance: false },
  { code: '20.01',  name: 'Основное производство',                                                offBalance: false },
  { code: '20.02',  name: 'Производство продукции из давальческого сырья',                       offBalance: false },
  { code: '20.04',  name: 'Собственные исследования и разработки',                                offBalance: false },

  { code: '21',     name: 'Полуфабрикаты собственного производства',                              offBalance: false },

  { code: '23',     name: 'Вспомогательные производства',                                         offBalance: false },
  { code: '23.01',  name: 'Вспомогательные производства',                                         offBalance: false },
  { code: '23.05',  name: 'Выполнение ремонтов основных средств',                                 offBalance: false },

  { code: '25',     name: 'Общепроизводственные расходы',                                         offBalance: false },
  { code: '26',     name: 'Общехозяйственные расходы',                                            offBalance: false },
  { code: '28',     name: 'Брак в производстве',                                                  offBalance: false },
  { code: '29',     name: 'Обслуживающие производства и хозяйства',                               offBalance: false },

  { code: '40',     name: 'Выпуск продукции (работ, услуг)',                                      offBalance: false },

  { code: '41',     name: 'Товары',                                                               offBalance: false },
  { code: '41.01',  name: 'Товары на складах',                                                   offBalance: false },
  { code: '41.02',  name: 'Товары в розничной торговле (по покупной стоимости)',                 offBalance: false },
  { code: '41.03',  name: 'Тара под товаром и порожняя',                                          offBalance: false },
  { code: '41.04',  name: 'Покупные изделия',                                                    offBalance: false },
  { code: '41.11',  name: 'Товары в розничной торговле (в АТТ по продажной стоимости)',          offBalance: false },
  { code: '41.12',  name: 'Товары в розничной торговле (в НТТ по продажной стоимости)',          offBalance: false },
  { code: '41.К',   name: 'Корректировка товаров прошлого периода',                               offBalance: false },

  { code: '42',     name: 'Торговая наценка',                                                  offBalance: false },
  { code: '42.01',  name: 'Торговая наценка в автоматизированных торговых точках',               offBalance: false },
  { code: '42.02',  name: 'Торговая наценка в неавтоматизированных торговых точках',            offBalance: false },

  // 43 – 59
  { code: '43',     name: 'Готовая продукция',                                                   offBalance: false },

  { code: '44',     name: 'Расходы на продажу',                                                  offBalance: false },
  { code: '44.01',  name: 'Издержки обращения в организациях, осуществляющих торговую деятельность', offBalance: false },
  { code: '44.02',  name: 'Коммерческие расходы в организациях, осуществляющих промышленную и иную производственную деятельность', offBalance: false },

  { code: '45',     name: 'Товары отгруженные',                                                  offBalance: false },
  { code: '45.01',  name: 'Покупные товары отгруженные',                                         offBalance: false },
  { code: '45.02',  name: 'Готовая продукция отгруженная',                                      offBalance: false },
  { code: '45.03',  name: 'Прочие товары отгруженные',                                          offBalance: false },
  { code: '45.04',  name: 'Переданные объекты недвижимости',                                     offBalance: false },

  { code: '46',     name: 'Выполненные этапы по незавершенным работам',                          offBalance: false },

  { code: '50',     name: 'Касса',                                                               offBalance: false },
  { code: '50.01',  name: 'Касса организации',                                                  offBalance: false },
  { code: '50.02',  name: 'Операционная касса',                                                 offBalance: false },
  { code: '50.03',  name: 'Денежные документы',                                                  offBalance: false },
  { code: '50.04',  name: 'Касса по деятельности платежного агента',                            offBalance: false },

  { code: '51',     name: 'Расчетные счета',                                                    offBalance: false },
  { code: '53',     name: 'Счет цифрового рубля',                                               offBalance: false },

  { code: '55',     name: 'Специальные счета в банках',                                          offBalance: false },
  { code: '55.01',  name: 'Аккредитивы',                                                        offBalance: false },
  { code: '55.02',  name: 'Чековые книжки',                                                     offBalance: false },
  { code: '55.03',  name: 'Депозитные счета',                                                    offBalance: false },
  { code: '55.04',  name: 'Прочие специальные счета',                                           offBalance: false },

  { code: '57',     name: 'Переводы в пути',                                                    offBalance: false },
  { code: '57.01',  name: 'Переводы в пути',                                                    offBalance: false },
  { code: '57.02',  name: 'Приобретение иностранной валюты',                                     offBalance: false },
  { code: '57.03',  name: 'Продажи по платежным картам',                                        offBalance: false },

  { code: '58',     name: 'Финансовые вложения',                                                offBalance: false },
  { code: '58.01',  name: 'Паи и акции',                                                        offBalance: false },
  { code: '58.01.1',name: 'Паи',                                                               offBalance: false },
  { code: '58.01.2',name: 'Акции',                                                             offBalance: false },
  { code: '58.02',  name: 'Долговые ценные бумаги',                                             offBalance: false },
  { code: '58.03',  name: 'Предоставленные займы',                                              offBalance: false },
  { code: '58.04',  name: 'Вклады по договору простого товарищества',                           offBalance: false },
  { code: '58.05',  name: 'Приобретенные права в рамках оказания финансовых услуг',               offBalance: false },

  { code: '59',     name: 'Резервы под обесценение финансовых вложений',                        offBalance: false },

  // 60 – 68.04.2 (уже были в вашем исходнике)
  { code: '60',     name: 'Расчеты с поставщиками и подрядчиками',                               offBalance: false },
  { code: '60.01',  name: 'Расчеты с поставщиками и подрядчиками',                               offBalance: false },
  { code: '60.02',  name: 'Расчеты по авансам выданным',                                         offBalance: false },
  { code: '60.03',  name: 'Векселя выданные',                                                   offBalance: false },

  { code: '62',     name: 'Расчеты с покупателями и заказчиками',                                offBalance: false },
  { code: '62.01',  name: 'Расчеты с покупателями и заказчиками',                                offBalance: false },
  { code: '62.02',  name: 'Расчеты по авансам полученным',                                      offBalance: false },
  { code: '62.03',  name: 'Векселя полученные',                                                 offBalance: false },
  { code: '62.ОТ',  name: 'Расчеты по авансам полученным в счет отгрузки',                      offBalance: false },
  { code: '62.ОТ.1',name: 'Расчеты по авансам полученным в счет отгрузки',                      offBalance: false },
  { code: '62.П',   name: 'Расчеты с розничными покупателями',                                  offBalance: false },

  { code: '66',     name: 'Расчеты по краткосрочным кредитам и займам',                         offBalance: false },
  { code: '66.01',  name: 'Краткосрочные кредиты',                                              offBalance: false },
  { code: '66.02',  name: 'Проценты по краткосрочным кредитам',                                 offBalance: false },
  { code: '66.03',  name: 'Краткосрочные займы',                                                 offBalance: false },
  { code: '66.04',  name: 'Проценты по краткосрочным займам',                                   offBalance: false },
  { code: '66.05',  name: 'Краткосрочные долговые ценные бумаги',                               offBalance: false },
  { code: '66.06',  name: 'Проценты по краткосрочным долговым ценным бумагам',                   offBalance: false },

  { code: '67',     name: 'Расчеты по долгосрочным кредитам и займам',                          offBalance: false },
  { code: '67.01',  name: 'Долгосрочные кредиты',                                               offBalance: false },
  { code: '67.02',  name: 'Проценты по долгосрочным кредитам',                                  offBalance: false },
  { code: '67.03',  name: 'Долгосрочные займы',                                                offBalance: false },
  { code: '67.04',  name: 'Проценты по долгосрочным займам',                                    offBalance: false },
  { code: '67.05',  name: 'Долгосрочные долговые ценные бумаги',                               offBalance: false },
  { code: '67.06',  name: 'Проценты по долгосрочным долговым ценным бумагам',                   offBalance: false },

  { code: '68',     name: 'Расчеты по налогам и сборам',                                         offBalance: false },
  { code: '68.01',  name: 'НДФЛ исчисленный налоговым агентом',                                offBalance: false },
  { code: '68.02',  name: 'Налог на добавленную стоимость',                                     offBalance: false },
  { code: '68.03',  name: 'Акцизы',                                                           offBalance: false },
  { code: '68.04',  name: 'Налог на прибыль',                                                   offBalance: false },
  { code: '68.04.1',name: 'Расчеты с бюджетом',                                                 offBalance: false },
  { code: '68.04.2',name: 'Расчет налога на прибыль',                                          offBalance: false },

  // 68.06 – 91.09 (добавляем оставшиеся забалансовые счета)
  { code: '68.06', name: 'Земельный налог',                                                      offBalance: false },
  { code: '68.07', name: 'Транспортный налог',                                                   offBalance: false },
  { code: '68.08', name: 'Налог на имущество',                                                   offBalance: false },
  { code: '68.09', name: 'Налог на рекламу',                                                     offBalance: false },
  { code: '68.10', name: 'Прочие налоги и сборы',                                                offBalance: false },
  { code: '68.11', name: 'Единый налог на вмененный доход',                                      offBalance: false },
  { code: '68.12', name: 'Налог при упрощенной системе налогообложения',                         offBalance: false },
  { code: '68.13', name: 'Торговый сбор',                                                       offBalance: false },
  { code: '68.14', name: 'Налог при патентной системе налогообложения',                          offBalance: false },
  { code: '68.15', name: 'Налог при Автоматизированной упрощенной системе налогообложения',     offBalance: false },
  { code: '68.16', name: 'Налог на профессиональный доход',                                      offBalance: false },
  { code: '68.17', name: 'Туристический налог',                                                  offBalance: false },
  { code: '68.21', name: 'НДФЛ индивидуального предпринимателя',                                offBalance: false },
  { code: '68.22', name: 'НДС по экспорту к возмещению',                                        offBalance: false },
  { code: '68.32', name: 'НДС при исполнении обязанностей налогового агента',                    offBalance: false },
  { code: '68.34', name: 'Налог на прибыль при исполнении обязанностей налогового агента',      offBalance: false },
  { code: '68.42', name: 'НДС при импорте товаров из Таможенного союза',                         offBalance: false },
  { code: '68.52', name: 'НДС налогового агента по отдельным видам товаров',                   offBalance: false },

  { code: '68.90', name: 'Единый налоговый счет',                                               offBalance: false },
  { code: '69',    name: 'Расчеты по социальному страхованию и обеспечению',                    offBalance: false },
  { code: '69.01', name: 'Расчеты по социальному страхованию',                                   offBalance: false },
  { code: '69.02', name: 'Расчеты по пенсионному обеспечению',                                   offBalance: false },
  { code: '69.02.1',name: 'Страховая часть трудовой пенсии',                                     offBalance: false },
  { code: '69.02.2',name: 'Накопительная часть трудовой пенсии',                                offBalance: false },
  { code: '69.02.3',name: 'Взносы на доплату к пенсии членам летных экипажей',                  offBalance: false },
  { code: '69.02.4',name: 'Взносы на доплату к пенсии работникам организаций угольной промышленности', offBalance: false },
  { code: '69.02.5',name: 'Дополнительные взносы на страховую часть пенсии работникам, занятым на работах с вредными условиями труда', offBalance: false },
  { code: '69.02.6',name: 'Дополнительные взносы на страховую часть пенсии работникам, занятым на работах с тяжелыми условиями труда', offBalance: false },
  { code: '69.02.7',name: 'Обязательное пенсионное страхование',                             offBalance: false },
  { code: '69.03',  name: 'Расчеты по обязательному медицинскому страхованию',                   offBalance: false },
  { code: '69.03.1',name: 'Федеральный фонд ОМС',                                                offBalance: false },
  { code: '69.03.2',name: 'Территориальный фонд ОМС',                                            offBalance: false },
  { code: '69.04',  name: 'ЕСН в части, перечисляемой в федеральный бюджет',                     offBalance: false },
  { code: '69.05',  name: 'Добровольные взносы на накопительную часть трудовой пенсии',         offBalance: false },
  { code: '69.05.1',name: 'Взносы за счет работодателя',                                       offBalance: false },
  { code: '69.05.2',name: 'Взносы, удерживаемые из доходов работника',                        offBalance: false },
  { code: '69.06',  name: 'Расчеты по страховым взносам, уплачиваемым исходя из стоимости страхового года', offBalance: false },
  { code: '69.06.1',name: 'Взносы в ПФР (страховая часть)',                                    offBalance: false },
  { code: '69.06.2',name: 'Взносы в ПФР (накопительная часть)',                                 offBalance: false },
  { code: '69.06.3',name: 'Взносы в ФОМС',                                                     offBalance: false },
  { code: '69.06.4',name: 'Взносы в ФСС',                                                      offBalance: false },
  { code: '69.06.5',name: 'Обязательное пенсионное страхование предпринимателя',               offBalance: false },
  { code: '69.06.6',name: 'Страховые взносы единый тариф ИП',                                  offBalance: false },
  { code: '69.07',  name: 'Страховые взносы по единому тарифу',                                offBalance: false },
  { code: '69.11',  name: 'Расчеты по обязательному социальному страхованию от несчастных случаев на производстве и профессиональных заболеваниях', offBalance: false },
  { code: '69.12',  name: 'Расчеты по добровольным взносам в ФСС на страхование работников на случай временной нетрудоспособности', offBalance: false },
  { code: '69.13',  name: 'Расчеты по средствам ФСС для страхователей, применяющих специальные режимы налогообложения', offBalance: false },
  { code: '69.13.1',name: 'Расчеты по средствам ФСС для страхователей, уплачивающих ЕНВД',        offBalance: false },
  { code: '69.13.2',name: 'Расчеты по средствам ФСС для страхователей, применяющих УСН',         offBalance: false },

  { code: '70',     name: 'Расчеты с персоналом по оплате труда',                                 offBalance: false },
  { code: '71',     name: 'Расчеты с подотчетными лицами',                                         offBalance: false },
  { code: '71.01',  name: 'Расчеты с подотчетными лицами',                                         offBalance: false },
  { code: '73',     name: 'Расчеты с персоналом по прочим операциям',                              offBalance: false },
  { code: '73.01',  name: 'Расчеты по предоставленным займам',                                    offBalance: false },
  { code: '73.02',  name: 'Расчеты по возмещению материального ущерба',                           offBalance: false },
  { code: '73.03',  name: 'Расчеты по прочим операциям',                                          offBalance: false },

  { code: '75',     name: 'Расчеты с учредителями',                                              offBalance: false },
  { code: '75.01',  name: 'Расчеты по вкладам в уставный (складочный) капитал',                   offBalance: false },
  { code: '75.02',  name: 'Расчеты по выплате доходов',                                          offBalance: false },

  { code: '76',     name: 'Расчеты с разными дебиторами и кредиторами',                           offBalance: false },
  { code: '76.01',  name: 'Расчеты по имущественному, личному и добровольному страхованию',      offBalance: false },
  { code: '76.01.1',name: 'Расчеты по имущественному и личному страхованию',                      offBalance: false },
  { code: '76.01.2',name: 'Платежи (взносы) по добровольному страхованию на случай смерти и причинения вреда здоровью', offBalance: false },
  { code: '76.01.9',name: 'Платежи (взносы) по прочим видам страхования',                       offBalance: false },
  { code: '76.02',  name: 'Расчеты по претензиям',                                              offBalance: false },
  { code: '76.03',  name: 'Расчеты по причитающимся дивидендам и другим доходам',                offBalance: false },
  { code: '76.04',  name: 'Расчеты по депонированным суммам',                                    offBalance: false },
  { code: '76.05',  name: 'Расчеты с прочими поставщиками и подрядчиками',                      offBalance: false },
  { code: '76.06',  name: 'Расчеты с прочими покупателями и заказчиками',                       offBalance: false },
  { code: '76.07',  name: 'Расчеты по аренде',                                                 offBalance: false },
  { code: '76.07.1',name: 'Арендные обязательства',                                             offBalance: false },
  { code: '76.07.2',name: 'Задолженность по арендным платежам',                                 offBalance: false },
  { code: '76.07.5',name: 'Проценты по аренде',                                                offBalance: false },
  { code: '76.07.9',name: 'НДС по арендным обязательствам',                                    offBalance: false },
  { code: '76.08',  name: 'Проценты по рассрочке',                                             offBalance: false },
  { code: '76.09',  name: 'Прочие расчеты с разными дебиторами и кредиторами',                  offBalance: false },
  { code: '76.10',  name: 'Прочие расчеты с физическими лицами',                                 offBalance: false },
  { code: '76.13',  name: 'Расчеты с факторинговыми компаниями',                                offBalance: false },
  { code: '76.14',  name: 'Приобретение билетов для командировок',                              offBalance: false },
  { code: '76.15',  name: 'Приобретение топливных карт',                                        offBalance: false },
  { code: '76.16',  name: 'Расчеты с самозанятыми по реестрам выплат',                          offBalance: false },
  { code: '76.17',  name: 'Расчеты по налогам с третьими лицами',                               offBalance: false },
  { code: '76.18',  name: 'Приобретение прав на использование результатов интеллектуальной деятельности', offBalance: false },
  { code: '76.41',  name: 'Расчеты по исполнительным документам работников',                     offBalance: false },
  { code: '76.49',  name: 'Расчеты по прочим удержаниям из заработной платы работников',         offBalance: false },
  { code: '76.AВ',  name: 'НДС по авансам и предоплатам',                                       offBalance: false },
  { code: '76.ВА',  name: 'НДС по авансам и предоплатам выданным',                            offBalance: false },
  { code: '76.К',   name: 'Корректировка расчетов прошлого периода',                            offBalance: false },
  { code: '76.НА',  name: 'Расчеты по НДС при исполнении обязанностей налогового агента',      offBalance: false },

  { code: '76.OT',  name: 'НДС, начисленный по отгрузке',                                         offBalance: false },
  { code: '77',     name: 'Отложенные налоговые обязательства',                                  offBalance: false },
  { code: '79',     name: 'Внутрихозяйственные расчеты',                                        offBalance: false },
  { code: '79.01',  name: 'Расчеты по выделенному имуществу',                                   offBalance: false },
  { code: '79.02',  name: 'Расчеты по текущим операциям',                                       offBalance: false },
  { code: '79.03',  name: 'Расчеты по договору доверительного управления имуществом',            offBalance: false },

  { code: '80',     name: 'Уставный капитал',                                                   offBalance: false },
  { code: '80.01',  name: 'Обыкновенные акции',                                                offBalance: false },
  { code: '80.02',  name: 'Привилегированные акции',                                            offBalance: false },
  { code: '80.09',  name: 'Прочий капитал',                                                     offBalance: false },  

  { code: '81',     name: 'Собственные акции (доли)',                                           offBalance: false },
  { code: '81.01',  name: 'Обыкновенные акции',                                                offBalance: false },
  { code: '81.02',  name: 'Привилегированные акции',                                            offBalance: false },
  { code: '81.09',  name: 'Прочий капитал',                                                     offBalance: false },  

  { code: '82',     name: 'Резервный капитал',                                                 offBalance: false },
  { code: '82.01',  name: 'Резервы, образованные в соответствии с законодательством',          offBalance: false },
  { code: '82.02',  name: 'Резервы, образованные в соответствии с учредительными документами', offBalance: false },

  { code: '83',     name: 'Добавочный капитал',                                                offBalance: false },
  { code: '83.01',  name: 'Прирост стоимости внеоборотных активов по переоценке',              offBalance: false },
  { code: '83.01.1',name: 'Прирост стоимости основных средств',                                offBalance: false },
  { code: '83.01.2',name: 'Прирост стоимости нематериальных активов',                         offBalance: false },
  { code: '83.01.3',name: 'Прирост стоимости прочих внеоборотных активов',                     offBalance: false },
  { code: '83.02',  name: 'Эмиссионный доход от выпуска обыкновенных акций',                    offBalance: false },
  { code: '83.03',  name: 'Эмиссионный доход от выпуска привилегированных акций',               offBalance: false },
  { code: '83.09',  name: 'Другие источники',                                                 offBalance: false },

  { code: '84',     name: 'Нераспределенная прибыль (непокрытый убыток)',                     offBalance: false },
  { code: '84.01',  name: 'Прибыль, подлежащая распределению',                                offBalance: false },
  { code: '84.02',  name: 'Убыток, подлежащий покрытию',                                       offBalance: false },
  { code: '84.03',  name: 'Нераспределенная прибыль в обращении',                             offBalance: false },
  { code: '84.04',  name: 'Нераспределенная прибыль использованная',                          offBalance: false },

  { code: '86',     name: 'Целевое финансирование',                                            offBalance: false },
  { code: '86.01',  name: 'Целевое финансирование из бюджета',                                 offBalance: false },
  { code: '86.02',  name: 'Прочее целевое финансирование и поступления',                       offBalance: false },

  { code: '90',     name: 'Продажи',                                                          offBalance: false },
  { code: '90.01',  name: 'Выручка',                                                         offBalance: false },
  { code: '90.01.1',name: 'Выручка по деятельности с основной системой налогообложения',       offBalance: false },

  { code: '90.01.2',name: 'Выручка по отдельным видам деятельности с особым порядком налогообложения', offBalance: false },
  { code: '90.02',  name: 'Себестоимость продаж',                                            offBalance: false },
  { code: '90.02.1',name: 'Себестоимость продаж по деятельности с основной системой налогообложения', offBalance: false },
  { code: '90.02.2',name: 'Себестоимость продаж по отдельным видам деятельности с особым порядком налогообложения', offBalance: false },
  { code: '90.03',  name: 'Налог на добавленную стоимость',                                  offBalance: false },
  { code: '90.04',  name: 'Акцизы',                                                        offBalance: false },
  { code: '90.05',  name: 'Экспортные пошлины',                                               offBalance: false },
  { code: '90.07',  name: 'Расходы на продажу',                                              offBalance: false },
  { code: '90.07.1',name: 'Расходы на продажу по деятельности с основной системой налогообложения', offBalance: false },
  { code: '90.07.2',name: 'Расходы на продажу по отдельным видам деятельности с особым порядком налогообложения', offBalance: false },
  { code: '90.08',  name: 'Управленческие расходы',                                          offBalance: false },
  { code: '90.08.1',name: 'Управленческие расходы по деятельности с основной системой налогообложения', offBalance: false },
  { code: '90.08.2',name: 'Управленческие расходы по отдельным видам деятельности с особым порядком налогообложения', offBalance: false },
  { code: '90.09',  name: 'Прибыль / убыток от продаж',                                       offBalance: false },

  { code: '91',     name: 'Прочие доходы и расходы',                                          offBalance: false },
  { code: '91.01',  name: 'Прочие доходы',                                                  offBalance: false },
  { code: '91.02',  name: 'Прочие расходы',                                                 offBalance: false },
  { code: '91.09',  name: 'Сальдо прочих доходов и расходов',                              offBalance: false },
  // ——————————————————————————————————————————————————————
  // Забалансовые счета (offBalance: true)
  { code: '001',     name: 'Арендованные основные средства',                                         offBalance: true },
  { code: '002',     name: 'Товарно-материальные ценности, принятые на ответственное хранение',      offBalance: true },
  { code: '003',     name: 'Материалы, принятые в переработку',                                       offBalance: true },
  { code: '003.01',  name: 'Материалы на складе',                                                    offBalance: true },
  { code: '003.02',  name: 'Материалы, переданные в производство',                                    offBalance: true },
  { code: '004',     name: 'Товары, принятые на комиссию',                                           offBalance: true },
  { code: '004.01',  name: 'Товары на складе',                                                      offBalance: true },
  { code: '004.02',  name: 'Товары, переданные на комиссию',                                       offBalance: true },
  { code: '004.K',   name: 'Корректировка комиссионных товаров прошлого периода',                   offBalance: true },
  { code: '005',     name: 'Оборудование, принятое для монтажа',                                     offBalance: true },
  { code: '006',     name: 'Бланки строгой отчетности',                                             offBalance: true },
  { code: '007',     name: 'Списанная в убыток задолженность неплатежеспособных дебиторов',         offBalance: true },
  { code: '008',     name: 'Обеспечения обязательств и платежей полученные',                         offBalance: true },
  { code: '008.01',  name: 'Обеспечения обязательств и платежей полученные',                         offBalance: true },
  { code: '009',     name: 'Обеспечения обязательств и платежей выданные',                          offBalance: true },
  { code: '009.01',  name: 'Обеспечения обязательств и платежей выданные',                          offBalance: true },
  { code: '010',     name: 'Износ основных средств',                                                offBalance: true },
  { code: '011',     name: 'Основные средства, сданные в аренду',                                  offBalance: true },
  { code: '012',     name: 'Возвратная тара',                                                      offBalance: true },
  { code: '012.01',  name: 'Возвратная тара на складе',                                            offBalance: true },
  { code: '012.02',  name: 'Возвратная тара у покупателя',                                         offBalance: true },
  { code: 'МЦ.02',   name: 'Спецодежда в эксплуатации',                                            offBalance: true },
  { code: 'МЦ.03',   name: 'Спецоснастка в эксплуатации',                                          offBalance: true },
  { code: 'МЦ.04',   name: 'Инвентарь и хозяйственные принадлежности в эксплуатации',               offBalance: true },
]

async function main() {
  for (const acc of accounts) {
    await prisma.account.upsert({
      where:  { code: acc.code },
      update: { name: acc.name, offBalance: acc.offBalance },
      create: { code: acc.code, name: acc.name, offBalance: acc.offBalance },
    })
  }
  console.log(`🔄 Seeded ${accounts.length} accounts`)
}

main()
  .catch(e => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })